name: Build and Deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to the required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Download model file from Google Drive
      run: |
        mkdir -p Implementation
        wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1OUcs0spykBEdNzFRHKAzkLnZAsseZm_0' -O Implementation/model_fer2013.h5

    - name: Verify installed packages
      run: pip freeze

    - name: Verify model file exists
      run: ls -l Implementation/

    - name: Run the app
      run: python app.py
