name: Build and Deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Sesuaikan jika perlu

    # Install dependencies with Numpy downgrade
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.23.5  # Downgrade Numpy
        pip install --no-cache-dir -r requirements.txt

    # Upgrade TensorFlow (opsional)
    - name: Upgrade TensorFlow
      run: pip install --upgrade tensorflow

    # Download model file from Google Drive
    - name: Download model file from Google Drive
      run: |
        mkdir -p Implementation
        wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1OUcs0spykBEdNzFRHKAzkLnZAsseZm_0' -O Implementation/model_fer2013.h5

    # Verify installed packages
    - name: Verify installed packages
      run: pip freeze

    # Verify that the model file exists
    - name: Verify model file exists
      run: ls -l Implementation/

    # Run the app with protobuf environment variable
    - name: Run the app
      env:
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      run: python app.py
