name: Build and Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Sesuaikan dengan versi Python Anda

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Menyimpan HTML statis di 'build/' yang dapat dipakai untuk GitHub Pages
      - name: Build Static Files
        run: |
          # Buat script untuk menggabungkan halaman statis saja di folder `build`
          mkdir -p build
          cp -r static/ templates/ build/

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy 🚀
        uses: actions/deploy-pages@v1
