name: Build and Deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to the required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install --no-cache-dir -r requirements.txt  # Install from requirements.txt without cache

    - name: Verify installed packages
      run: pip freeze  # Verify that Flask and other dependencies are installed

    - name: Run the app
      run: python app.py  # Start your application
